-- Vue matérialisée pour l'analyse sectorielle
CREATE MATERIALIZED VIEW MV_SECTOR_ACTIVITY AS
SELECT 
    g.CD_REFNIS_REGION,
    g.TX_NAME_FR as NOM_REGION,
    n.CD_LEVEL as NIVEAU_NACE,
    n.TX_ACTIVITY_FR as SECTEUR_ACTIVITE,
    d.CD_YEAR,
    SUM(f.MS_ACTIVE_VAT_COUNT) as TOTAL_ENTREPRISES,
    SUM(f.MS_NET_VAT_CREATION) as CREATION_NETTE,
    ROUND(SUM(f.MS_NET_VAT_CREATION) * 100.0 / NULLIF(SUM(f.MS_ACTIVE_VAT_COUNT), 0), 2) as TAUX_CREATION_NET
FROM FACT_NACE_EMPLOYMENT f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_ECONOMIC_ACTIVITY n ON f.CD_ECONOMIC_ACTIVITY = n.CD_ECONOMIC_ACTIVITY
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
GROUP BY 
    g.CD_REFNIS_REGION,
    g.TX_NAME_FR,
    n.CD_LEVEL,
    n.TX_ACTIVITY_FR,
    d.CD_YEAR;