-- Vue excluant automatiquement les totaux pour les analyses détaillées
CREATE VIEW V_UNEMPLOYMENT_DETAILED AS
SELECT f.*, 
    ag.TX_AGE_GROUP_FR,
    ag.CD_AGE_MIN,
    ag.CD_AGE_MAX
FROM FACT_UNEMPLOYMENT f
JOIN DIM_AGE_GROUP ag ON f.CD_AGE_GROUP = ag.CD_AGE_GROUP
WHERE ag.FL_TOTAL = FALSE;

-- Vue matérialisée pour les analyses régionales
CREATE MATERIALIZED VIEW MV_UNEMPLOYMENT_BY_REGION AS
SELECT 
    g.CD_REFNIS_REGION,
    g.TX_NAME_FR as NOM_REGION,
    d.CD_YEAR,
    d.CD_QUARTER,
    ag.FL_TOTAL,
    ag.TX_AGE_GROUP_FR,
    ut.TX_UNEMPLOYMENT_TYPE_FR as TYPE_CHOMAGE,
    ROUND(AVG(f.MS_VALUE) * 100, 2) as TAUX_CHOMAGE
FROM FACT_UNEMPLOYMENT f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_AGE_GROUP ag ON f.CD_AGE_GROUP = ag.CD_AGE_GROUP
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
JOIN DIM_UNEMPLOYMENT_TYPE ut ON f.CD_UNEMPLOYMENT_TYPE = ut.CD_UNEMPLOYMENT_TYPE
GROUP BY 
    g.CD_REFNIS_REGION, 
    g.TX_NAME_FR,
    d.CD_YEAR,
    d.CD_QUARTER,
    ag.FL_TOTAL,
    ag.TX_AGE_GROUP_FR,
    ut.TX_UNEMPLOYMENT_TYPE_FR
ORDER BY 
    g.CD_REFNIS_REGION,
    d.CD_YEAR,
    d.CD_QUARTER;