-- Insertion des nouvelles sources de données immobilières
INSERT INTO metadata.dim_source (
    cd_source,
    cd_type,
    tx_file_pattern,
    tx_file_path,
    tx_file_format,
    tx_delimiter,
    tx_encoding,
    tx_name_fr,
    tx_description_fr,
    cd_frequency,
    dt_data_start,
    dt_data_end,
    cd_reference_year,
    cd_geographic_level,
    tx_provider,
    fl_active
) VALUES 
('IMMO_MUNTY_1990_1999', 
    'FILE',
    'immo_by_municipality_1990-1999.csv',
    '/Users/sarahdinari/Desktop/data_lake/real_estate/immo_by_municipality/',
    'CSV',
    ',',
    'UTF-8',
    'Immobilier par commune 1990-1999',
    'Statistiques immobilières par commune pour la période 1990-1999',
    'YEARLY',
    '1990-01-01',      
    '1999-12-31',      
    1990,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('IMMO_MUNTY_2000_2009', 
    'FILE',
    'immo_by_municipality_2000-2009.csv',
    '/Users/sarahdinari/Desktop/data_lake/real_estate/immo_by_municipality/',
    'CSV',
    ',',
    'UTF-8',
    'Immobilier par commune 2000-2009',
    'Statistiques immobilières par commune pour la période 2000-2009',
    'YEARLY',
    '2000-01-01',      
    '2009-12-31',     
    2000,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('IMMO_MUNTY_2010_2019', 
    'FILE',
    'immo_by_municipality_2010-2019.csv',
    '/Users/sarahdinari/Desktop/data_lake/real_estate/immo_by_municipality/',
    'CSV',
    ',',
    'UTF-8',
    'Immobilier par commune 2010-2019',
    'Statistiques immobilières par commune pour la période 2010-2019',
    'YEARLY',
    '2010-01-01',      
    '2019-12-31',      
    2010,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('IMMO_MUNTY_1980_1989', 
    'FILE',
    'immo_by_municipality_1980-1989.csv',
    '/Users/sarahdinari/Desktop/data_lake/real_estate/immo_by_municipality/',
    'CSV',
    ',',
    'UTF-8',
    'Immobilier par commune 1980-1989',
    'Statistiques immobilières par commune pour la période 1980-1989',
    'YEARLY',
    '1980-01-01',      
    '1989-12-31',      
    1980,              
    'MUNICIPALITY',
    'STATBEL',
    true
);