-- D'abord, supprimons l'ancienne entrée si elle existe
DELETE FROM metadata.dim_source WHERE cd_source = 'VAT_NACE_EMPL';

-- Ensuite, insérons les nouvelles entrées, une par année
INSERT INTO metadata.dim_source (
    cd_source,
    cd_type,
    tx_file_pattern,
    tx_file_path,
    tx_file_format,
    tx_delimiter,
    tx_encoding,
    tx_name_fr,
    tx_description_fr,
    cd_frequency,
    dt_data_start,
    dt_data_end,
    cd_reference_year,
    cd_geographic_level,
    tx_provider,
    fl_active
) VALUES 
('VAT_NACE_EMPL_2008', 
    'FILE',
    'TF_VAT_NACE_EMPL_2008.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2008',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2008',
    'YEARLY',
    '2008-01-01',      
    '2008-12-31',      
    2008,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2009', 
    'FILE',
    'TF_VAT_NACE_EMPL_2009.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2009',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2009',
    'YEARLY',
    '2009-01-01',      
    '2009-12-31',     
    2009,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2010', 
    'FILE',
    'TF_VAT_NACE_EMPL_2010.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2010',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2010',
    'YEARLY',
    '2010-01-01',      
    '2010-12-31',      
    2010,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2011', 
    'FILE',
    'TF_VAT_NACE_EMPL_2011.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2011',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2011',
    'YEARLY',
    '2011-01-01',      
    '2011-12-31',      
    2011,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2013', 
    'FILE',
    'TF_VAT_NACE_EMPL_2013.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2013',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2013',
    'YEARLY',
    '2013-01-01',      
    '2013-12-31',      
    2013,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2014', 
    'FILE',
    'TF_VAT_NACE_EMPL_2014.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2014',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2014',
    'YEARLY',
    '2014-01-01',      
    '2014-12-31',      
    2014,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2015', 
    'FILE',
    'TF_VAT_NACE_EMPL_2015.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2015',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2015',
    'YEARLY',
    '2015-01-01',      
    '2015-12-31',      
    2015,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2016', 
    'FILE',
    'TF_VAT_NACE_EMPL_2016.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2016',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2016',
    'YEARLY',
    '2016-01-01',      
    '2016-12-31',      
    2016,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2017', 
    'FILE',
    'TF_VAT_NACE_EMPL_2017.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2017',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2017',
    'YEARLY',
    '2017-01-01',      
    '2017-12-31',      
    2017,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2018', 
    'FILE',
    'TF_VAT_NACE_EMPL_2018.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2018',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2018',
    'YEARLY',
    '2018-01-01',      
    '2018-12-31',      
    2018,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2019', 
    'FILE',
    'TF_VAT_NACE_EMPL_2019.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2019',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2019',
    'YEARLY',
    '2019-01-01',      
    '2019-12-31',      
    2019,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2020', 
    'FILE',
    'TF_VAT_NACE_EMPL_2020.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2020',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2020',
    'YEARLY',
    '2020-01-01',      
    '2020-12-31',      
    2020,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2021', 
    'FILE',
    'TF_VAT_NACE_EMPL_2021.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2021',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2021',
    'YEARLY',
    '2021-01-01',      
    '2021-12-31',      
    2021,              
    'MUNICIPALITY',
    'STATBEL',
    true
),
('VAT_NACE_EMPL_2023', 
    'FILE',
    'TF_VAT_NACE_EMPL_2023.csv',
    '/Users/sarahdinari/Desktop/data_lake/employment_unemployment/TF_VAT_NACE_EMPL/',
    'CSV',
    ',',
    'UTF-8',
    'Emploi par secteur NACE 2023',
    'Données sur l''emploi selon la TVA par secteur NACE pour l''année 2023',
    'YEARLY',
    '2023-01-01',      
    '2023-12-31',      
    2023,              
    'MUNICIPALITY',
    'STATBEL',
    true
);