-- Script généré le 2025-02-20
-- Insertion des sources de données de population

BEGIN;

-- Vérification de l'existence de la table
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables 
                WHERE table_schema = 'metadata' 
                AND table_name = 'dim_source') THEN
        RAISE EXCEPTION 'La table metadata.dim_source n''existe pas!';
    END IF;
END $$;

-- Suppression des anciennes entrées pour ces sources si elles existent
DELETE FROM metadata.dim_source
WHERE cd_source LIKE 'POP_STRUCT_%'
AND cd_source != 'POP_STRUCT_2024';  -- On garde 2024 qui existe déjà

-- Insertion des nouvelles sources
INSERT INTO metadata.dim_source (
    cd_source,
    cd_type,
    tx_file_pattern,
    tx_file_path,
    tx_file_format,
    tx_delimiter,
    tx_encoding,
    tx_name_fr,
    tx_description_fr,
    cd_frequency,
    dt_data_start,
    dt_data_end,
    cd_reference_year,
    cd_geographic_level,
    tx_provider,
    fl_active
) VALUES
('POP_STRUCT_2009',
'FILE',
'TF_SOC_POP_STRUCT_2009.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2009',
'Données sur la structure de la population par commune pour l''année 2009',
'YEARLY',
'2009-01-01',
'2009-12-31',
2009,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2010',
'FILE',
'TF_SOC_POP_STRUCT_2010.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2010',
'Données sur la structure de la population par commune pour l''année 2010',
'YEARLY',
'2010-01-01',
'2010-12-31',
2010,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2011',
'FILE',
'TF_SOC_POP_STRUCT_2011.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2011',
'Données sur la structure de la population par commune pour l''année 2011',
'YEARLY',
'2011-01-01',
'2011-12-31',
2011,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2012',
'FILE',
'TF_SOC_POP_STRUCT_2012.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2012',
'Données sur la structure de la population par commune pour l''année 2012',
'YEARLY',
'2012-01-01',
'2012-12-31',
2012,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2013',
'FILE',
'TF_SOC_POP_STRUCT_2013.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2013',
'Données sur la structure de la population par commune pour l''année 2013',
'YEARLY',
'2013-01-01',
'2013-12-31',
2013,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2014',
'FILE',
'TF_SOC_POP_STRUCT_2014.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2014',
'Données sur la structure de la population par commune pour l''année 2014',
'YEARLY',
'2014-01-01',
'2014-12-31',
2014,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2015',
'FILE',
'TF_SOC_POP_STRUCT_2015.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2015',
'Données sur la structure de la population par commune pour l''année 2015',
'YEARLY',
'2015-01-01',
'2015-12-31',
2015,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2016',
'FILE',
'TF_SOC_POP_STRUCT_2016.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2016',
'Données sur la structure de la population par commune pour l''année 2016',
'YEARLY',
'2016-01-01',
'2016-12-31',
2016,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2018',
'FILE',
'TF_SOC_POP_STRUCT_2018.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2018',
'Données sur la structure de la population par commune pour l''année 2018',
'YEARLY',
'2018-01-01',
'2018-12-31',
2018,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2019',
'FILE',
'TF_SOC_POP_STRUCT_2019.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2019',
'Données sur la structure de la population par commune pour l''année 2019',
'YEARLY',
'2019-01-01',
'2019-12-31',
2019,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2021',
'FILE',
'TF_SOC_POP_STRUCT_2021.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2021',
'Données sur la structure de la population par commune pour l''année 2021',
'YEARLY',
'2021-01-01',
'2021-12-31',
2021,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2022',
'FILE',
'TF_SOC_POP_STRUCT_2022.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2022',
'Données sur la structure de la population par commune pour l''année 2022',
'YEARLY',
'2022-01-01',
'2022-12-31',
2022,
'MUNICIPALITY',
'STATBEL',
true),

('POP_STRUCT_2023',
'FILE',
'TF_SOC_POP_STRUCT_2023.csv',
'/Users/sarahdinari/Desktop/data_lake/population/',
'CSV',
',',
'UTF-8',
'Structure de la population 2023',
'Données sur la structure de la population par commune pour l''année 2023',
'YEARLY',
'2023-01-01',
'2023-12-31',
2023,
'MUNICIPALITY',
'STATBEL',
true);

COMMIT;
