-- Vue matérialisée pour l'analyse des revenus moyens par région
CREATE MATERIALIZED VIEW MV_REGIONAL_INCOME_ANALYSIS AS
SELECT 
    d.CD_YEAR,
    g.CD_REFNIS_REGION,
    g.TX_NAME_FR as NOM_REGION,
    SUM(f.MS_TOT_NET_TAXABLE_INC) as REVENU_IMPOSABLE_TOTAL,
    SUM(f.MS_TOT_NET_INC) as REVENU_NET_TOTAL,
    SUM(f.MS_TOT_TAXES) as TAXES_TOTALES,
    ROUND(AVG(f.MS_AVG_NET_INC_PER_DECL), 2) as REVENU_MOYEN_PAR_DECLARANT,
    ROUND(AVG(f.MS_AVG_TAX_PER_DECL), 2) as TAXE_MOYENNE_PAR_DECLARANT,
    ROUND(AVG(f.MS_TAX_RATE) * 100, 2) as TAUX_IMPOSITION_MOYEN
FROM FACT_TAXES f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
WHERE g.CD_LEVEL = 2  -- Niveau régional
GROUP BY d.CD_YEAR, g.CD_REFNIS_REGION, g.TX_NAME_FR
ORDER BY d.CD_YEAR, g.CD_REFNIS_REGION;

-- Vue matérialisée pour l'analyse des sources de revenus
CREATE MATERIALIZED VIEW MV_INCOME_SOURCES_ANALYSIS AS
SELECT 
    d.CD_YEAR,
    g.CD_REFNIS_REGION,
    g.TX_NAME_FR as NOM_REGION,
    SUM(f.MS_REAL_ESTATE_NET_INC) as REVENUS_IMMOBILIERS,
    SUM(f.MS_TOT_NET_MOV_ASS_INC) as REVENUS_MOBILIERS,
    SUM(f.MS_TOT_NET_VARIOUS_INC) as REVENUS_DIVERS,
    SUM(f.MS_TOT_NET_PROF_INC) as REVENUS_PROFESSIONNELS,
    ROUND(SUM(f.MS_REAL_ESTATE_NET_INC) * 100.0 / SUM(f.MS_TOT_NET_INC), 2) as PCT_IMMOBILIER,
    ROUND(SUM(f.MS_TOT_NET_MOV_ASS_INC) * 100.0 / SUM(f.MS_TOT_NET_INC), 2) as PCT_MOBILIER,
    ROUND(SUM(f.MS_TOT_NET_VARIOUS_INC) * 100.0 / SUM(f.MS_TOT_NET_INC), 2) as PCT_DIVERS,
    ROUND(SUM(f.MS_TOT_NET_PROF_INC) * 100.0 / SUM(f.MS_TOT_NET_INC), 2) as PCT_PROFESSIONNEL
FROM FACT_TAXES f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
WHERE g.CD_LEVEL = 2  -- Niveau régional
GROUP BY d.CD_YEAR, g.CD_REFNIS_REGION, g.TX_NAME_FR
ORDER BY d.CD_YEAR, g.CD_REFNIS_REGION;