-- Vue matérialisée pour l'analyse de la pression fiscale
CREATE MATERIALIZED VIEW MV_TAX_PRESSURE_ANALYSIS AS
SELECT 
    d.CD_YEAR,
    g.CD_REFNIS_REGION,
    g.TX_NAME_FR as NOM_REGION,
    SUM(f.MS_TOT_STATE_TAXES) as IMPOTS_ETAT,
    SUM(f.MS_TOT_MUNICIP_TAXES) as TAXES_COMMUNALES,
    SUM(f.MS_TOT_SUBURBS_TAXES) as TAXES_AGGLOMERATION,
    ROUND(SUM(f.MS_TOT_STATE_TAXES) * 100.0 / SUM(f.MS_TOT_TAXES), 2) as PCT_ETAT,
    ROUND(SUM(f.MS_TOT_MUNICIP_TAXES) * 100.0 / SUM(f.MS_TOT_TAXES), 2) as PCT_COMMUNAL,
    ROUND(SUM(f.MS_TOT_SUBURBS_TAXES) * 100.0 / SUM(f.MS_TOT_TAXES), 2) as PCT_AGGLOMERATION,
    ROUND(SUM(f.MS_TOT_TAXES) * 100.0 / SUM(f.MS_TOT_NET_TAXABLE_INC), 2) as TAUX_PRESSION_FISCALE
FROM FACT_TAXES f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
WHERE g.CD_LEVEL = 2  -- Niveau régional
GROUP BY d.CD_YEAR, g.CD_REFNIS_REGION, g.TX_NAME_FR
ORDER BY d.CD_YEAR, g.CD_REFNIS_REGION; 