-- Vues matérialisées pour les analyses courantes

-- Vue des tendances de cohabitation par région
CREATE MATERIALIZED VIEW MV_COHABITATION_BY_REGION AS
SELECT 
    g.CD_REFNIS_REGION,
    g.TX_NAME_FR as NOM_REGION,
    c.TX_COHABITATION_FR,
    d.CD_YEAR,
    SUM(f.MS_PEOPLE_COUNT) as TOTAL_PERSONNES,
    ROUND(SUM(f.MS_PEOPLE_COUNT) * 100.0 / SUM(SUM(f.MS_PEOPLE_COUNT)) OVER (PARTITION BY g.CD_REFNIS_REGION, d.CD_YEAR), 2) as POURCENTAGE
FROM FACT_HOUSEHOLD_COHABITATION f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_COHABITATION_STATUS c ON f.CD_COHABITATION = c.CD_COHABITATION
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
WHERE g.CD_LEVEL = 2  -- Niveau régional
GROUP BY g.CD_REFNIS_REGION, g.TX_NAME_FR, c.TX_COHABITATION_FR, d.CD_YEAR;

-- Vue des tendances de cohabitation par groupe d'âge
CREATE MATERIALIZED VIEW MV_COHABITATION_BY_AGE AS
SELECT 
    a.CD_AGE_GROUP,
    c.TX_COHABITATION_FR,
    d.CD_YEAR,
    SUM(f.MS_PEOPLE_COUNT) as TOTAL_PERSONNES,
    ROUND(SUM(f.MS_PEOPLE_COUNT) * 100.0 / SUM(SUM(f.MS_PEOPLE_COUNT)) OVER (PARTITION BY a.CD_AGE_GROUP, d.CD_YEAR), 2) as POURCENTAGE
FROM FACT_HOUSEHOLD_COHABITATION f
JOIN DIM_AGE a ON f.CD_AGE = a.CD_AGE
JOIN DIM_COHABITATION_STATUS c ON f.CD_COHABITATION = c.CD_COHABITATION
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
GROUP BY a.CD_AGE_GROUP, c.TX_COHABITATION_FR, d.CD_YEAR;