-- Vues matérialisées pour les analyses courantes

-- Vue par niveau administratif
CREATE MATERIALIZED VIEW MV_VEHICLES_BY_ADMIN_LEVEL AS
SELECT 
    g.CD_LEVEL,
    CASE g.CD_LEVEL
        WHEN 1 THEN 'National'
        WHEN 2 THEN 'Régional'
        WHEN 3 THEN 'Provincial'
        WHEN 4 THEN 'District'
        WHEN 5 THEN 'Communal'
        WHEN 6 THEN 'Secteur'
    END as NIVEAU_ADMINISTRATIF,
    g.TX_NAME_FR as NOM_ZONE,
    d.CD_YEAR,
    SUM(f.MS_HOUSEHOLD_COUNT) as TOTAL_MENAGES,
    SUM(f.MS_VEHICLE_COUNT) as TOTAL_VEHICULES,
    ROUND(SUM(f.MS_VEHICLE_COUNT)::DECIMAL / NULLIF(SUM(f.MS_HOUSEHOLD_COUNT), 0), 2) as MOYENNE_VEHICULES_PAR_MENAGE
FROM FACT_HOUSEHOLD_VEHICLES f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
GROUP BY g.CD_LEVEL, g.TX_NAME_FR, d.CD_YEAR
ORDER BY g.CD_LEVEL, g.TX_NAME_FR;

-- Vue des zones à forte motorisation
CREATE MATERIALIZED VIEW MV_HIGH_MOTORIZATION_AREAS AS
SELECT 
    g.TX_NAME_FR as NOM_COMMUNE,
    d.CD_YEAR,
    f.MS_HOUSEHOLD_COUNT as TOTAL_MENAGES,
    f.MS_VEHICLE_COUNT as TOTAL_VEHICULES,
    f.MS_AVG_VEHICLE_PER_HOUSEHOLD as MOYENNE_VEHICULES_PAR_MENAGE
FROM FACT_HOUSEHOLD_VEHICLES f
JOIN DIM_GEOGRAPHY g ON f.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_DATE d ON f.ID_DATE = d.ID_DATE
WHERE 
    g.CD_LEVEL = 5  -- Niveau communal
    AND f.MS_AVG_VEHICLE_PER_HOUSEHOLD > (
        SELECT AVG(MS_AVG_VEHICLE_PER_HOUSEHOLD) * 1.2  -- 20% au-dessus de la moyenne
        FROM FACT_HOUSEHOLD_VEHICLES f2
        JOIN DIM_GEOGRAPHY g2 ON f2.ID_GEOGRAPHY = g2.ID_GEOGRAPHY
        WHERE g2.CD_LEVEL = 5
    )
ORDER BY f.MS_AVG_VEHICLE_PER_HOUSEHOLD DESC;