 -- Vue matérialisée par commune et groupe d'âge
CREATE MATERIALIZED VIEW MV_POPULATION_BY_MUNICIPALITY_AGE AS
SELECT 
    p.ID_GEOGRAPHY,
    g.TX_NAME_FR as NOM_COMMUNE,
    a.CD_AGE_GROUP,
    d.CD_YEAR,
    SUM(p.MS_PEOPLE_COUNT) as TOTAL_POPULATION
FROM FACT_POPULATION_STRUCTURE p
JOIN DIM_GEOGRAPHY g ON p.ID_GEOGRAPHY = g.ID_GEOGRAPHY
JOIN DIM_AGE a ON p.CD_AGE = a.CD_AGE
JOIN DIM_DATE d ON p.ID_DATE = d.ID_DATE
GROUP BY p.ID_GEOGRAPHY, g.TX_NAME_FR, a.CD_AGE_GROUP, d.CD_YEAR;